### ISSUE TITLE
Práctica 

### ISSUE THREAD

**Issue by LuisAlexisMorales** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-LuisAlexisMorales#1]
[mate discreta-1.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-LuisAlexisMorales/files/12592318/mate.discreta-1.pdf)

**Comment by 00Asaf00** [comment]
Portada: 40% (Muy vacía la portada)
Procedimiento: 30%
Figuras-Ilustraciones-Fotografías: 60%
Resultados y conclusiones: 60%

Calificación: 0.2*47.5 = 10

**Comment by josealfredo79** [comment]
Revisado...
